stages:
  - build
  - deploy

variables:
  DEV_DEPLOY_DIR: '/var/host/www/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/www-$CI_COMMIT_REF_NAME'

build:
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - public/
  only:
    - master
  script:
    - yarn
    - env > .env
    - export APP_ENV="preview"
    - export APP_BACKEND_URL="https://boilerplate12345.kozhin.dev"
#    - export APP_SENTRY_DSN="REPLACE_WITH_REAL_SENTRY_DSN"
    - node webpack production
    - echo "$CI_COMMIT_REF_NAME-$CI_JOB_ID" > $CI_PROJECT_DIR/public/version.txt

deploy_dev:
  stage: deploy
  only:
    - master
  tags:
    - dev-server
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p $DEV_DEPLOY_DIR
    - rsync --recursive --remove-source-files --delete ./ $DEV_DEPLOY_DIR

