stages:
  - lint
  - build
  - deploy

variables:
  DEV_SSR_DEPLOY_DIR: '/var/www/steroids-steroids-site/www-master'
  DEV_SSR_PROCESS: 'steroids-site-ssr-dev'
  # PROD_SSR_DEPLOY_DIR: '/var/www/steroids-steroids-site/www-master'
  # PROD_SSR_PROCESS: 'steroids-site-ssr-prod'

lint:
  stage: lint
  script:
    - yarn
    - yarn lint

.build_ssr:
  cache:
    paths:
      - node_modules
  stage: build
  artifacts:
    paths:
      - public
      - node_modules
  script:
    - yarn
    - yarn run build-ssr
    - echo "$CI_COMMIT_REF_NAME-$CI_JOB_ID" > $CI_PROJECT_DIR/public/version.txt

build_ssr_dev:
  extends: .build_ssr
  only:
    - master
  variables:
    APP_SSR_PORT: 9993
    APP_ENV: preview

build_ssr_prod:
  extends: .build_ssr
  only:
    - prod
  variables:
    APP_SSR_PORT: 9993
    APP_ENV: production

.deploy_ssr:
  stage: deploy
  tags:
    - dev-server
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p $DEPLOY_DIR
    - rsync
      --recursive
      --remove-source-files
      --include=public/***
      --include=node_modules/***
      --exclude='*'
      --delete
      ./ $DEPLOY_DIR
    # - sudo -i pm2 reload --update-env $SSR_PROCESS_NAME

deploy_ssr_dev:
  extends: .deploy_ssr
  only:
    - master
  variables:
    DEPLOY_DIR: $DEV_SSR_DEPLOY_DIR
    SSR_PROCESS_NAME: $DEV_SSR_PROCESS

deploy_ssr_prod:
    stage: deploy
    only:
        - prod
    script:
        - ssh prod "mkdir -p $PROD_SSR_DEPLOY_DIR"
        - rsync
            --recursive
            --remove-source-files
            --include=public/***
            --include=backend/***
            --include=node_modules/***
            --exclude='*'
            --delete
            $CI_PROJECT_DIR/ prod:$PROD_SSR_DEPLOY_DIR
        # - ssh prod "
        #     cd $PROD_SSR_DEPLOY_DIR
        #     && rm -f $PROD_SSR_ROOT_DIR/current
        #     && ln -sf $PROD_SSR_DEPLOY_DIR $PROD_SSR_ROOT_DIR/current
        #     && sudo -i pm2 reload $PROD_SSR_PROCESS || exit 0"

