export const icons = {
    kozhinDev: require('./svgs/kozhinDev.svg'),
    logo: require('./svgs/logo.svg'),
    searchAlt: require('./svgs/search_alt.svg'),
    light: require('./svgs/light.svg'),
    dark: require('./svgs/dark.svg'),
    decoration1: require('./svgs/decoration1.svg'),
    decoration2: require('./svgs/decoration2.svg'),
    decoration3: require('./svgs/decoration3.svg'),
    decoration4: require('./svgs/decoration4.svg'),
    decoration5: require('./svgs/decoration5.svg'),
    decoration6: require('./svgs/decoration6.svg'),
    decoration7: require('./svgs/decoration7.svg'),
    decoration8: require('./svgs/decoration8.svg'),
    burger: require('./svgs/burger.svg'),
    featureIcon: require('./svgs/feature-icon.svg'),
    featureIconBlack: require('./svgs/feature-icon-black.svg'),
};
